openapi: 3.0.0
info:
  title: batch
  version: "1.0.0"
paths:
  /wp-json/batch/v1:
    post:
      responses:
        "200":
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                validation:
                  type: string
                requests:
                  type: array
                  items:
                    type: object
                    properties:
                      method:
                        type: string
                      path:
                        type: string
                      body:
                        type: object
                        properties:
                          title:
                            type: string
                      headers:
                        type: object
